# Pipeline Job (Spark)
apiVersion: batch/v1
kind: Job
metadata:
  name: ecom-pipeline-job-spark
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pipeline
          image: ecom-pipeline:dev
          imagePullPolicy: Never
          command: ["python", "pipeline/run_pipeline_spark.py"]
          env:
            - name: PYTHONPATH
              value: /app
          resources:
            requests:
              memory: "1Gi"
              cpu:    "500m"
            limits:
              memory: "2Gi"
              cpu:    "1000m"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: output-volume
              mountPath: /app/output
      volumes:
        - name: data-volume
          hostPath:
            path: /data
            type: Directory
        - name: output-volume
          hostPath:
            path: /output
            type: DirectoryOrCreate
